project:
  type: website

website:
  title: "micabo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - about.qmd

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    toc: true



